In [2]:
import numpy as np

## datatypes and attributes

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2,3)) # shift  + tab show to us what the function does
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype # float64 is the default datatype

dtype('float64')

In [19]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array= np.random.randint(0, 10, size = (3, 5))
random_array

array([[9, 6, 2, 4, 2],
       [3, 1, 4, 0, 7],
       [8, 3, 9, 0, 6]])

In [21]:
random_array.size # 3 * 5 = 5

15

In [22]:
random_array.shape # (3, 5)

(3, 5)

In [23]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.00859459, 0.26844859, 0.47462111],
       [0.68448129, 0.18825182, 0.38612575],
       [0.96913327, 0.33759695, 0.97212883],
       [0.21902434, 0.23200854, 0.91522663],
       [0.70096071, 0.58396806, 0.32600476]])

In [24]:
random_array_2.shape

(5, 3)

## Manipulating and comparing arrays

### arithmetic

In [25]:
a1

array([1, 2, 3])

In [26]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
ones * 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
a1*a1

array([1, 4, 9])

In [29]:
a1

array([1, 2, 3])

In [30]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [32]:
np.multiply(a2, a3)

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [33]:
# floor division
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [34]:
a2 ** 2 # power or np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

### aggregating 

In [35]:
# create big array
big_array = np.random.random(10000)
big_array.size

10000

In [36]:
%timeit sum(big_array)
%timeit np.sum(big_array)

2.54 ms ± 187 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
12.2 µs ± 1.36 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [37]:
small_list = [1, 2, 3]
sum(small_list)

6

In [38]:
np.sum(small_list)

6

In [39]:
np.random.seed(0)
# making two array with random numbers
#between 1 and 10of the same shape
first_matrix = np.random.randint(1, 10, (2, 3)) 
second_matrix = np.random.randint(1, 10, (2, 3))
first_matrix, second_matrix

(array([[6, 1, 4],
        [4, 8, 4]]),
 array([[6, 3, 5],
        [8, 7, 9]]))

In [40]:
np.multiply(first_matrix, second_matrix)

array([[36,  3, 20],
       [32, 56, 36]])

In [41]:
np.multiply(first_matrix, second_matrix)

array([[36,  3, 20],
       [32, 56, 36]])

In [42]:
#dot product

In [43]:
np.dot(first_matrix, second_matrix)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
second_matrix.T

In [ ]:
second_matrix = second_matrix.T
second_matrix

In [ ]:
result_matrix = np.dot(first_matrix, second_matrix.T)
result_matrix

In [ ]:
result_matrix

In [ ]:
result_matrix.shape

In [ ]:
first_matrix.shape, second_matrix.shape, result_matrix.shape

In [ ]:
second_matrix.dtype

In [ ]:
np.dot(first_matrix, second_matrix)

In [44]:
import pandas as pd

In [45]:
products = pd.Series(["motherboards", "business software", "flowers software" ])
products

0         motherboards
1    business software
2     flowers software
dtype: object

In [50]:
np.random.seed(10)
sales = np.random.randint(0, 100, (3, 6))
sales

array([[ 9, 15, 64, 28, 89, 93],
       [29,  8, 73,  0, 40, 36],
       [16, 11, 54, 88, 62, 33]])

In [54]:
months = pd.Series(["January", "February", "March", "April", "May", "June"])
sales_data = pd.DataFrame(sales, index = products, columns = months)
sales_data

January  February  March  April  May  June
motherboards             9        15     64     28   89    93
business software       29         8     73      0   40    36
flowers software        16        11     54     88   62    33

In [74]:
costs = np.array([50, 3000, 2600])

In [62]:
sales_data = sales_data.T

In [63]:
sales_data

motherboards  business software  flowers software
January              9                 29                16
February            15                  8                11
March               64                 73                54
April               28                  0                88
May                 89                 40                62
June                93                 36                33

In [86]:
costs = np.array([50, 3000, 2600])
costs = pd.DataFrame(costs.reshape(1, 3), index = ["total"], columns = ["motherboards", "biz", "flowers"])
costs

motherboards   biz  flowers
total            50  3000     2600

In [96]:
total_first_sem = np.dot(sales_data, costs.T)
total_first_sem

array([[129050],
       [ 53350],
       [362600],
       [230200],
       [285650],
       [198450]])

In [102]:
sales_data["total semester ($)"] = total_first_sem
sales_data

motherboards  business software  flowers software  total semester  \
January              9                 29                16          129050   
February            15                  8                11           53350   
March               64                 73                54          362600   
April               28                  0                88          230200   
May                 89                 40                62          285650   
June                93                 36                33          198450   

          total semester ($)  
January               129050  
February               53350  
March                 362600  
April                 230200  
May                   285650  
June                  198450

In [103]:
del sales_data["total semester"]
sales_data

motherboards  business software  flowers software  \
January              9                 29                16   
February            15                  8                11   
March               64                 73                54   
April               28                  0                88   
May                 89                 40                62   
June                93                 36                33   

          total semester ($)  
January               129050  
February               53350  
March                 362600  
April                 230200  
May                   285650  
June                  198450

## images into matrix

<img src="panda.png" />

In [105]:
from matplotlib.image import imread

In [106]:
panda = imread("panda.png")

In [110]:
panda[:2]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

In [111]:
panda.size

24465000

In [112]:
panda.shape

(2330, 3500, 3)

In [113]:
panda.ndim

3

In [114]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [120]:
first_array = np.array([1, 2, 3,])
second_array = np.array([5, 4, 3])
first_array == second_array

array([False, False,  True])

In [126]:
first_array = np.array([1, 2, 3,])
second_array = np.array([[1, 4, 3], [5, 6, 3]])
first_array < second_array

array([[False,  True, False],
       [ True,  True, False]])

In [134]:
# creating a random array
random_array = np.random.randint(0, 20, (4, 5))
random_array

array([[ 9, 19, 16, 19,  5],
       [15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14],
       [ 7,  0,  1,  9,  0]])

In [135]:
# sorting the random array
sorted_array = np.sort(random_array)
sorted_array

array([[ 5,  9, 16, 19, 19],
       [ 0,  3, 15, 15, 18],
       [14, 17, 19, 19, 19],
       [ 0,  0,  1,  7,  9]])

In [152]:
random_array

array([[ 9, 19, 16, 19,  5],
       [15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14],
       [ 7,  0,  1,  9,  0]])

In [162]:
np.argmax(random_array[2], axis = 0)

1